# Generated by Django 5.2.6 on 2025-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tester', '0002_nikkei225data_portfolio_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('FTSE_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('SNP500_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('NIKKEI225_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount_invested', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('change_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
        ),
    ]
