# Generated by Django 5.2.6 on 2025-09-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tester', '0003_portfolios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='change_percentage',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='total_amount_invested',
        ),
    ]
