# Generated by Django 5.2.6 on 2025-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tester', '0004_remove_portfolios_change_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='change_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfolios',
            name='total_amount_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
