# Generated by Django 5.2.6 on 2025-09-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tester', '0008_portfolios_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolios',
            old_name='author',
            new_name='user',
        ),
    ]
