# Generated by Django 5.2.6 on 2025-09-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tester', '0005_portfolios_change_percentage_portfolios_final_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolios',
            name='change_percentage',
        ),
        migrations.RemoveField(
            model_name='portfolios',
            name='total_amount_invested',
        ),
    ]
